services:
  - type: web
    name: logs-sse-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: ALLOWED_ORIGINS
        value: "*" 